### ISSUE TITLE
Change default conf file path

### ISSUE THREAD

**Issue by matveevandrey** [SpookOz/zabbix-wininventory#1]
By default (with msi installer) zabbix agent conf file is located in the same directory where it has been install 

Do you mind to change $ZabbixConfFile in ps1 files accordingly?

**Comment by SpookOz** [comment]
Hi. Are you using Zabbix agent v4 or v5? I noticed in v5, it actually places the $ZabbixConfFile in ProgramData. That's why I have 2 versions (2020 and v5).

**Comment by matveevandrey** [comment]
I've tested v.5.0 LTS Release. It stores config in Zabbix bin directory
Conf dir path is the only the difference in these two versions?

Thanks

**Comment by SpookOz** [comment]
Hm. Strange. In every Windows install I have, when I upgraded to v5x, it moved the zabbix_agentd.conf and zabbix_agentd.userparams.conf to %programdata%\zabbix. Maybe it was in 5.1 or 5.2?

That's the only difference I think. Try the v4 ps script and see if it works for you.
